### ISSUE TITLE
Updating PyCTM based on a forked repo?

### ISSUE THREAD

**Issue by adbedada** [kzhai/PyCTM#1]
Hi @kzhai 

I recently noticed that user @fdtomasi has u[pgraded PyCTM to Python-3](https://github.com/kzhai/PyCTM/compare/master...fdtomasi:master) and made some useful changes to the package. Will you be interested in merging his work and/or releasing a distribution file?
I would like to help you bring PyCTM to Anaconda's[ Conda-forge channel ](https://github.com/conda-forge)so that it can reach larger community of developers and data scientists.

**Comment by adbedada** [comment]
Hi @fdtomasi 
I reached out to the owner of the source for PyCTM if he is interested in updating the software based on the changes you made. Will you be okay with that, if he makes the change? 

If @kzhai wanted to keep it as is, would you mind creating a [release](https://github.com/fdtomasi/PyCTM/releases) for your work? 

In that case, we can bring PyCTM to Anaconda's [Conda-forge channe](https://github.com/conda-forge)l where it can reach larger audience.

**Comment by kzhai** [comment]
Hi, @adbeda 
Thanks for reaching out, I am perfectly fine to merge the changes from @fdtomasi. Let me know how he wants to proceed. Thanks!

**Comment by adbedada** [comment]
@kzhai awesome. If you then release tarballs, it w'd be easy for the conda-forge community to accept it since its from the original source code.

I just went ahead created a PR. hopefully, if you both agree in merging it, we can move on to the next step :)

**Comment by fdtomasi** [comment]
Hi @adbeda and @kzhai. Thank you for your interest in my few modifications!
I am super happy to merge my forked project here. I can finish to port the repo to Python 3 as there are some files I didn't modify yet. Anyway until the PR is open I can add some more commits there soon. Thank you!

**Comment by adbedada** [comment]
Awesome. Thank you both @kzhai and @fdtomasi. We'll keep it open until you (@fdtomasi) are done upgrading it. Before we forget and move on to other stuffs, I thought we (more specifically, you too ,lol) can work around in releasing the first version soon, if its okay for both of you.  This is exciting!

**Comment by adbedada** [comment]
@kzhai we would need a license to include. do you have any preference? MIT, Apache-2.0 (e.g. Tensorflow) , BSD-2.0 or 3.0 -Clause (e.g., scikit) are some of the most commonly used Open Source Licenses. 
@fdtomasi used [BSD approved](https://github.com/kzhai/PyCTM/blob/master/setup.py#L25) in the setup.py file, which I can go ahead and include but just want to double check with you. 

The BSD-2.0-Clause License looks something like:

```
The 2-Clause BSD License
  SPDX short identifier: BSD-2-Clause
        

Copyright <2019> <Zhai, Ke>

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or other
materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Read on this, add or remove anything you like.

Best,

-Eddie

**Comment by kzhai** [comment]
Sure. I normally go with Apache by default, but BSD works okay for me. Let us go with BSD then.

Best,
Ke
